# Generated by Django 5.0.2 on 2024-03-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productshots',
            old_name='image',
            new_name='image1',
        ),
        migrations.RemoveField(
            model_name='productshots',
            name='alt',
        ),
        migrations.AddField(
            model_name='productshots',
            name='image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productshots',
            name='image3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productshots',
            name='image4',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
