# Generated by Django 5.0.2 on 2024-02-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_product_item_slug_productitem_item_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='item_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
