# Generated by Django 5.0.2 on 2024-02-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_new_price_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='productshots',
            name='alt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
