# Generated by Django 5.0.2 on 2024-02-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_product_slug_alter_productitem_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='item_slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
