# Generated by Django 5.0.2 on 2024-03-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_subcategory_product_sub_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategory',
            new_name='Style',
        ),
        migrations.AlterModelOptions(
            name='style',
            options={'verbose_name_plural': 'Styles'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='style',
        ),
    ]
