# Generated by Django 5.0.2 on 2024-02-16 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_review_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 0, 38, 11, 389942)),
        ),
    ]
