# Generated by Django 5.0.2 on 2024-02-16 20:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_review_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='star',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
